# Generated by Django 3.2.5 on 2021-07-04 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 4, 16, 2, 58, 537692, tzinfo=utc)),
        ),
    ]
